### PR TITLE
Make pasting on Linux more robust, close #65

### LINKED ISSUE #65: More robust pasting
Hello,

I notice that ATM, we use `Ctrl+v` for pasting. Quite a few apps (e.g. emacs, terminal) use that for something else. It seems that a much safer method (used by CopyQ) is to use `Shift+Insert`. 
https://github.com/zachcurry/emacs-anywhere/blob/05bf8ef119834d330803bdad91f9028ff87cc7b9/bin/linux#L47

Perhaps this should be used instead?

### PR DESCRIPTION
**Pull request by tecosaur**
As stated in #65 this seems to be more robust

### CODE REVIEW

**Comment by zachcurry** [comment]
@tecosaur It would be cool to make the keyboard shortcut configurable. Feel free to send a pull request.

**Comment by tecosaur** [comment]
I mean, I guess that would be nice, it just seems unnecessary to me. I use CopyQ a lot, and have never had an issue with that pasting; it uses <kbd>Shift+Insert</kbd>. However <kbd>Ctrl+V</kbd> is rebound in a fair few apps, notably most terminals.

**Comment by tecosaur** [comment]
@zachcurry would be good if you could follow up on my previous comment :slightly_smiling_face:

**Comment by zachcurry** [comment]
Sorry for the delay, @tecosaur.

You may be right. As someone who only uses Linux for a production environment, I don't know all of the ways in which a user might configure their environment, or if certain issues may arise from which applications use PRIMARY and which applications use CLIPBOARD with Shift+Insert, etc. Making this configurable would give the user, the one who knows more about their environment and use case(s), more control over how the paste operation works; however, since simply hardcoding Shift+Insert seems to be preferable to hardcoding Ctrl+v, I will go ahead and merge your pull request and table the potential corner cases for a later date.

**Pull request merged**
