### PR TITLE
Use XDG home and add colour

### LINKED ISSUE #38: Support XDG Base Directory Specification
**Linux only**

Hey.  I think it would be cool to support XDG BDS to avoid unnecessary littering of home directory.  The binaries can also automatically install into user's bin directory so they will "just work" without need to adding anything to `$PATH` etc.

https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

### PR DESCRIPTION
**Pull request by tecosaur**
This closes #38, and makes the script nicer to look at.

image

### CODE REVIEW

**Comment by zachcurry** [comment]
Thanks for this, @tecosaur! I will look this over as soon as I get a chance.

**Comment by tecosaur** [comment]
@zachcurry I hope you get a chance soon :)

**Comment by tecosaur** [comment]
@zachcurry maybe around the Christmas holidays, you might have a little spare time? :eyes:

**Comment by tecosaur** [comment]
Hi @zachcurry :slightly_smiling_face: I tried sending you an email (using your git commit address) two weeks ago.

It would be great to hear if you've recieved it.

**Comment by tecosaur** [comment]
I've done a little re-implementation of the ideas here, [tecosaur/emacs-everywhere](https://github.com/tecosaur/emacs-everywhere).

As such, I now consider this PR redundant.

**Comment by psibi** [comment]
@tecosaur Note that I have another fork which uses a different clipboard mechanism that the one used here: https://github.com/psibi/emacs-everywhere

**Comment by tecosaur** [comment]
I see, you just type the contents. I'm not sure how well it would work for large buffers, but seems reasonable. With a bit of extra work, the clipboard approach is working consistently for me though.

**Comment by psibi** [comment]
So far I haven't had any issues. :-) But the problem I had with the old approach was:

* It interfered with my other clipboard
* It wasn't reliable at all. It never worked consistently for me.

Eitherwise, let me know if you do change the clipboard approach or make it configurable to add additional approaches. I would like to avoid relying on my fork if possible. :-)

**Comment by tecosaur** [comment]
In my rewrite, most of `emacs-everywhere-finish` is clipboard-related, but you could just add advice to replace that function.
Another thought, I could check the clipboard contents immediately before overwriting, and then restore the clipboard content to that original state.
Assuming you're on Linux, I'd be curious to know if you still have the reliability issues with my package, if you'd be willing to test it out and let me know that would be great :)

**Comment by psibi** [comment]
@tecosaur Sure, I will give it a try in a couple of days. I will open an issue in your issue tracker in case if something doesn't work. Thanks you!

**Comment by tecosaur** [comment]
> let me know if you do change the clipboard approach or make it configurable to add additional approaches

I've recently pushed https://github.com/tecosaur/emacs-everywhere/commit/d20adad4b43c36c2d0b53630f09d3948cac2a916 which introduces some new `defcustom`s:
- `emacs-everywhere-paste-command`
- `emacs-everywhere-copy-command`
- `emacs-everywhere-window-focus-command`

This may be enough, and if not I'm open to a PR adding support for further customisation.

**Comment by psibi** [comment]
@tecosaur I gave this a try today and it doesn't seem be working in my setup. This was my session:

```
❯ emacsclient --eval "(emacs-everywhere)"
nil

~/Downloads via 🦀 v1.57.0
❯

```

As you can see that it didn't put anything in my terminal after pressing `C-x 5 0`. Probably I should open an github issue instead ?

**Pull request closed without merging**
