### PR TITLE
Linux support WIP. Needs to be tested on Linux

### PR DESCRIPTION
**Pull request by zachcurry**
The `linux-support` branch was written blindly outside of Linux and **needs to be tested**. I would prefer we start with Ubuntu and GNU Emacs and then work our way out to less common pairings. This branch has a dependency on `xdotools` now, so you'll need to make sure you've got that installed on your machine before you start testing.

Clone the repo, checkout `linux-support`, run the `install` script, and assign a keyboard shortcut to run `~/.emacs_anywhere/bin/run` script.  Post you findings here and we'll work through any issues we come across.

🤞

### CODE REVIEW

**Comment by zachcurry** [comment]
Whoops! forgot to link to issue [#7](https://github.com/zachcurry/emacs-anywhere/issues/7)

**Comment by zeltak** [comment]
Hi

i currently testing it (on arch linux, dont have Ubuntu)

it installed well, and the emacs frame opens with the hotkey, yet i think for me its not pasting the content from the *emacs-anywhere* buffer. i tried both issuing M-x `delete-frame` and killing the frame via the OS with no success
Very happy to keep on debugging!

thx for your awesome work!

Z

**Comment by zachcurry** [comment]
@zeltak Thanks you so much for testing this! I have added a new commit to try to fix the paste functionality. If you get a chance, could you pull these new changes, install once more, and see if this works for you?

**Comment by zachcurry** [comment]
I'm currently testing this in Ubuntu and need to make some changes for it to work...

**Comment by zachcurry** [comment]
@zeltak  Thanks so much for lending a hand on this! If my changes didn't fix it on your machine open an issue and we'll work through it.

**Comment by zeltak** [comment]
Hi @zachcurry 

thx for your continuous work on this awesome project :D 

i updated from git and installed again but cant seem to get it to paste after i kill the emacs frame
im using up to date arch with xdotool 3.20160805.1-1 

should i open a new issue?

thx
Z

**Comment by zachcurry** [comment]
@zeltak open a new issue. Thanks!

**Pull request merged**
